#!/usr/bin/env python3
import pwd
import grp
import os

def parse_args():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument('-u', '--user', required=True)
    ap.add_argument('-g', '--group')
    ap.add_argument('cmd', nargs='+')
    return ap.parse_args()

def main():
    args = parse_args()

    p = pwd.getpwnam(args.user)
    uid = p.pw_uid
    gid = p.pw_gid

    if args.group:
        g = grp.getgrnam(args.group)
        gid = g.gr_gid

    os.setgroups([])
    os.setgid(gid)
    os.setuid(uid)

    os.execvp(args.cmd[0], args.cmd)

main()
